import Head from 'next/head'

export default function Header({...props }) {
    return (
        <Head>
            <title>{props.title?props.title:"hello next.js"}</title>
            <base href={process.env.NEXT_PUBLIC_AppDomain} />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/media/logo.svg" />
            <link
            rel="stylesheet"
            href="https://use.fontawesome.com/releases/v5.13.1/css/all.css"
            integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q"
            crossorigin="anonymous"
            />
        </Head>
    )
}
